{"name": "test_1_login_error[error_phone2]", "status": "passed", "parameters": [{"name": "error_phone", "value": "{'phone': '1868472055', 'pwd': 'python', 'expect': '请输入正确的手机号'}"}], "start": 1568898309928, "stop": 1568898310311, "uuid": "3186f6a2-8622-4fcc-bd61-a6b670f2ca48", "historyId": "a592acf9695b9ebf74cadb8fe2475c1f", "testCaseId": "e8c1f96b3a1ee5611ba6f39770dbf5d5", "fullName": "cases.test_login.TestLogin#test_1_login_error", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "zhzhuwang"}, {"name": "thread", "value": "19908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}