{"name": "test_1_login_error[error_phone1]", "status": "passed", "parameters": [{"name": "error_phone", "value": "{'phone': '12345678901', 'pwd': 'python', 'expect': '请输入正确的手机号'}"}], "start": 1568898209715, "stop": 1568898210119, "uuid": "8ac69e5e-26b1-44df-bd17-08d8113606e7", "historyId": "2f4346fe27db97cd0a591227c3567bca", "testCaseId": "e8c1f96b3a1ee5611ba6f39770dbf5d5", "fullName": "cases.test_login.TestLogin#test_1_login_error", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "zhzhuwang"}, {"name": "thread", "value": "18764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}